# Mendefinisikan Variable

sepatu_A = 400000
sepatu_B = 350000
harga_diskonA = sepatu_A - (sepatu_A * 13/100)
harga_diskonB = sepatu_B - (sepatu_B * 21/100)

# Menjumlahkan 

print("harga sepatu A adalah", sepatu_A)
print("harga sepatu B adalah", sepatu_B)
print("sepatu A mendapatkan diskon 13% sehingga harganya menjadi", int(harga_diskonA))
print("sepatu B mendapatkan diskon 21% sehingga harganya menjadi", int(harga_diskonB))
